Clockwork.Vault.WebApp/Controllers/ImportData/TidalDataImportController.cs
using System.Configuration;
using System.Threading.Tasks;
using System.Web.Mvc;
using Clockwork.Vault.Integrations.Tidal.Orchestration;

namespace Clockwork.Vault.WebApp.Controllers.ImportData
{
    public class TidalDataImportController : Controller
    {
        private SaveTidalDataOrchestrator _orchestrator;

        public TidalDataImportController()
        {
            var appSettingsReader = new AppSettingsReader();
            var token = appSettingsReader.GetValue("tidal.token", typeof(string)) as string;
            var username = appSettingsReader.GetValue("tidal.username", typeof(string)) as string;
            var password = appSettingsReader.GetValue("tidal.password", typeof(string)) as string;
            _orchestrator = new SaveTidalDataOrchestrator(token, username, password);
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> SavePlaylists()
        {
            var result = await _orchestrator.SavePlaylists();
            return View("~/Views/Shared/Result.cshtml", result);
        }

        public async Task<ActionResult> SaveUserFavPlaylists()
        {
            var result = await _orchestrator.SaveUserFavPlaylists();
            return View("~/Views/Shared/Result.cshtml", result);
        }

        public async Task<ActionResult> SaveUserFavAlbums()
        {
            var result = await _orchestrator.SaveUserFavAlbums();
            return View("~/Views/Shared/Result.cshtml", result);
        }

        public async Task<ActionResult> SaveUserFavTracks()
        {
            var result = await _orchestrator.SaveUserFavTracks();
            return View("~/Views/Shared/Result.cshtml", result);
        }

        public async Task<ActionResult> SaveUserFavArtists()
        {
            var result = await _orchestrator.SaveUserFavArtists();
            return View("~/Views/Shared/Result.cshtml", result);
        }

        public async Task<ActionResult> EnsureAlbumUpc()
        {
            var iterationSettings = new IterationSettings
            {
                SleepTimeInSeconds = 1
            };
            var result = await _orchestrator.EnsureAlbumUpc(iterationSettings);
            return View("~/Views/Shared/Result.cshtml", result);
        }

        public async Task<ActionResult> EnsureTrackIsrc()
        {
            var iterationSettings = new IterationSettings
            {
                SleepTimeInSeconds = 1
            };
            var result = await _orchestrator.EnsureTrackIsrc(iterationSettings);
            return View("~/Views/Shared/Result.cshtml", result);
        }
    }
}

Clockwork.Vault.WebApp/Controllers/SanitizeData/TidalDataSanitizeController.cs
using System.Linq;
using System.Web.Mvc;
using Clockwork.Vault.Core.Models;
using Clockwork.Vault.Query.Tidal;

namespace Clockwork.Vault.WebApp.Controllers.SanitizeData
{
    public class TidalDataSanitizeController : Controller
    {
        private readonly TidalOrchestrator _tidalOrchestrator;

        public TidalDataSanitizeController()
        {
            _tidalOrchestrator = new TidalOrchestrator();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FindDuplicateArtists()
        {
            var tidalArtists = _tidalOrchestrator.Artists;

            var groups = tidalArtists.GroupBy(a => a.Name);

            var log = new Log { Title = "Tidal: Duplicate artists" };

            foreach (var g in groups.Where(g => g.Count() > 1))
            {
                log.Statistics.Add($"{g.Key}: {g.Count()}");
            }

            return View("~/Views/Shared/Result.cshtml", log);
        }

        public ActionResult FindDuplicateAlbums()
        {
            var tidalArtists = _tidalOrchestrator.Albums;

            var groups = tidalArtists.GroupBy(a => a.Title);

            var log = new Log { Title = "Tidal: Duplicate albums" };

            foreach (var g in groups.Where(g => g.Count() > 1))
            {
                log.Statistics.Add($"{g.Key}: {g.Count()}");
            }

            return View("~/Views/Shared/Result.cshtml", log);
        }
    }
}

Clockwork.Vault.WebApp/Controllers/TidalController.cs
using System.Web.Mvc;
using Clockwork.Vault.Query.Tidal;

namespace Clockwork.Vault.WebApp.Controllers
{
    public class TidalController : Controller
    {
        private readonly TidalOrchestrator _tidalOrchestrator;

        public TidalController()
        {
            _tidalOrchestrator = new TidalOrchestrator();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Artists(int? id)
        {
            if (id.HasValue)
            {
                var artist = _tidalOrchestrator.GetArtistExpanded(id.Value);

                if (artist != null)
                    return View("~/Views/Tidal/Artist.cshtml", artist);

                return View("~/Views/Shared/NotFound.cshtml");
            }

            return View(_tidalOrchestrator.GetArtistsOrderedByNameGroupedByIsFavorite());
        }

        [HttpGet]
        public ActionResult Albums(int? id)
        {
            if (id.HasValue)
            {
                var album = _tidalOrchestrator.GetAlbumExpanded(id.Value);

                if (album != null)
                    return View("~/Views/Tidal/Album.cshtml", album);
                
                return View("~/Views/Shared/NotFound.cshtml");
            }

            return View(_tidalOrchestrator.GetAlbumsOrderedByTitleGroupedByIsFavorite());
        }

        [HttpGet]
        public ActionResult Tracks(int? id)
        {
            if (id.HasValue)
            {
                var track = _tidalOrchestrator.GetTrackExpanded(id.Value);

                if (track != null)
                    return View("~/Views/Tidal/Track.cshtml", track);

                return View("~/Views/Shared/NotFound.cshtml");
            }

            return View(_tidalOrchestrator.GetTracksOrderedByTitleGroupedByIsFavorite());
        }

        [HttpGet]
        public ActionResult Playlists(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var playlist = _tidalOrchestrator.GetPlaylistExpanded(id);

                if (playlist != null)
                    return View("~/Views/Tidal/Playlist.cshtml", playlist);

                return View("~/Views/Shared/NotFound.cshtml");
            }

            return View(_tidalOrchestrator.GetPlaylistsGroupedByCreator());
        }
    }
}

Clockwork.Vault.WebApp/Controllers/TidalToMasterController.cs
using System.Web.Mvc;
using Clockwork.Vault.Dao;
using Clockwork.Vault.DataTransfer.TidalToMaster;

namespace Clockwork.Vault.WebApp.Controllers
{
    public class TidalToMasterController : Controller
    {
        private VaultContext _vaultContext;

        private TidalToMasterDataOrchestrator Orchestrator => new TidalToMasterDataOrchestrator(_vaultContext);

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TransferArtists()
        {
            GetInMemContextOrEstablish();
            var vm = Orchestrator.TransferArtists();
            return View("~/Views/Shared/Result.cshtml", vm);
        }

        public ActionResult TransferAlbums()
        {
            GetInMemContextOrEstablish();
            var vm = Orchestrator.TransferAlbums();
            return View("~/Views/Shared/Result.cshtml", vm);
        }

        public ActionResult TransferTracks()
        {
            GetInMemContextOrEstablish();
            var vm = Orchestrator.TransferTracks();
            return View("~/Views/Shared/Result.cshtml", vm);
        }

        public ActionResult TransferPlaylists()
        {
            GetInMemContextOrEstablish();
            var vm = Orchestrator.TransferPlaylists();
            return View("~/Views/Shared/Result.cshtml", vm);
        }

        public ActionResult TransferAlbumArtists()
        {
            GetInMemContextOrEstablish();
            var vm = Orchestrator.TransferAlbumArtists();
            return View("~/Views/Shared/Result.cshtml", vm);
        }

        private void GetInMemContextOrEstablish() => _vaultContext = new VaultContext();
    }
}

Clockwork.Vault.WebApp/Views/Shared/NotFound.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Not Found</title>
</head>
<body>
    <h1>Not Found</h1>
</body>
</html>

Clockwork.Vault.WebApp/Views/Shared/Result.cshtml
@model Clockwork.Vault.Core.Models.Log

<h2>@Model.Title</h2>

<ul>
    @foreach (var msg in Model.Statistics)
    {
        <li>@msg</li>
    }
</ul>
    -------------------------------------
<ul>
    @foreach (var msg in Model.Messages)
    {
        var strings = msg.Split('\t');
        var numberOfIndents = strings.Length - 1;
        if (numberOfIndents == 0)
        {
            <li>@msg</li>
        }
        else
        {
            <li>
                @for (var i = 0; i < numberOfIndents; i++)
                {
                    @:<ul><li>
                }
                @msg
                @for (var j = 0; j < numberOfIndents; j++)
                {
                    @:</li></ul>
                }
            </li>
        }
    }
</ul>

Clockwork.Vault.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clockwork Vault</title>
    <link rel="stylesheet" href="/Content/Site.css"/>
</head>
<body>
    <header>
        <h2>Clockwork Vault</h2>
        <menu id="main-menu">
            <ul>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>
                    Data Import
                    <ul>
                        <li>@Html.ActionLink("Tidal Data Import", "Index", "TidalDataImport")</li>
                    </ul>
                </li>
                <li>
                    Data Sanitization
                    <ul>
                        <li>@Html.ActionLink("Tidal Data Sanitization", "Index", "TidalDataSanitize")</li>
                    </ul>
                </li>
                <li>
                    Data Movement
                    <ul>
                        <li>@Html.ActionLink("Tidal to Master", "Index", "TidalToMaster")</li>
                    </ul>
                </li>
                <li>
                    View Data
                    <ul>
                        <li>@Html.ActionLink("View Tidal Data", "Index", "Tidal")</li>
                    </ul>
                </li>
            </ul>
        </menu>
    </header>
    <div id="main">
        @RenderBody()
    </div>
<footer>
    <p>Clockwork Vault</p>
</footer>
</body>
</html>